name: Release

on: [push, pull_request]
# on:
#   release:
#       types: [published]

jobs:
  win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: checkout
      run: git checkout $("${{ github.ref }}" | sed -r 's .*/.*/(.*) \1 g')
    - name: install
      run: |
        set-executionpolicy remotesigned -s cu
        iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
        scoop install curl 7zip erlang
        $env:path + ";" + $env:USERPROFILE + "\scoop\shims"
    - name: build
      run: |
        make emqx
        ./_build/emqx/rel/emqx/bin/emqx start
        ./_build/emqx/rel/emqx/bin/emqx stop
    
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install curl zip gnu-sed erlang
        echo "/usr/local/bin:$PATH" >> ~/.bashrc
    - name: build
      run: |
        refs=$(echo ${{ github.ref }} | gsed -r  "s .*/.*/(.*) \1 g")
        EMQX_DEPS_DEFAULT_VSN=$refs make emqx
        ./_build/emqx/rel/emqx/bin/emqx start
        ./_build/emqx/rel/emqx/bin/emqx stop
