name: Release

on: [push, pull_request]

jobs:
  win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: $GITHUB_REF
        fetch-depth: 1
    - name: install
      run: |
        set-executionpolicy remotesigned -s cu
        iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
        scoop install curl 7zip erlang
        make emqx
    
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      env:
        EMQX_DEPS_DEFAULT_VSN: $GITHUB_REF
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install curl zip erlang
        make emqx
